import type { Listing, Profile } from "@/types";

export const SAMPLE_AGENT: Profile = {
  id: "agent-001",
  full_name: "Budi Santoso",
  email: "budi@rentara.id",
  phone_whatsapp: "6281234567890",
  avatar_url: null,
  role: "agent",
  is_verified: true,
  created_at: "2024-01-01T00:00:00Z",
};

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "listing-001",
    agent_id: "agent-001",
    title: "Luxury Studio at Sudirman Suites",
    description:
      "Sophisticated studio apartment in the heart of Jakarta's CBD. Floor-to-ceiling windows with panoramic city views. Recently renovated with premium finishes.",
    price_monthly: 8500000,
    area: "SCBD",
    address: "Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan",
    lat: -6.2277,
    lng: 106.8089,
    bedrooms: 0,
    bathrooms: 1,
    size_sqm: 28,
    furnished: "fully-furnished",
    is_pet_friendly: false,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "WiFi", "Security 24/7", "Gym", "Pool", "Elevator"],
    created_at: "2024-10-01T00:00:00Z",
    updated_at: "2024-10-15T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-002",
    agent_id: "agent-001",
    title: "Modern 2BR Townhouse Kemang",
    description:
      "Beautifully designed townhouse in Kemang's most sought-after enclave. Private garden, two dedicated parking spots, pet-friendly compound.",
    price_monthly: 18000000,
    area: "Kemang",
    address: "Jl. Kemang Raya No. 12, Jakarta Selatan",
    lat: -6.2613,
    lng: 106.8152,
    bedrooms: 2,
    bathrooms: 2,
    size_sqm: 95,
    furnished: "semi-furnished",
    is_pet_friendly: true,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "Parking", "Garden", "Security 24/7", "Water Heater"],
    created_at: "2024-09-15T00:00:00Z",
    updated_at: "2024-10-10T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-003",
    agent_id: "agent-001",
    title: "Cozy 1BR Apartment Menteng",
    description:
      "Classic Dutch colonial-era neighborhood with modern apartment living. Walking distance to embassies and Menteng Park.",
    price_monthly: 12000000,
    area: "Menteng",
    address: "Jl. HOS Cokroaminoto No. 5, Jakarta Pusat",
    lat: -6.1944,
    lng: 106.8338,
    bedrooms: 1,
    bathrooms: 1,
    size_sqm: 45,
    furnished: "fully-furnished",
    is_pet_friendly: false,
    is_verified: false,
    status: "active",
    photos: [],
    amenities: ["AC", "WiFi", "Parking", "Water Heater"],
    created_at: "2024-10-05T00:00:00Z",
    updated_at: "2024-10-05T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-004",
    agent_id: "agent-001",
    title: "Executive 3BR in BSD City",
    description:
      "Spacious family home in BSD City's green township. Close to international schools and Aeon Mall. Brand new development.",
    price_monthly: 22000000,
    area: "BSD",
    address: "The Zora, BSD City, Tangerang Selatan",
    lat: -6.3044,
    lng: 106.6536,
    bedrooms: 3,
    bathrooms: 3,
    size_sqm: 180,
    furnished: "semi-furnished",
    is_pet_friendly: true,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "Parking", "Pool", "Gym", "Security 24/7", "Garden", "CCTV"],
    created_at: "2024-09-20T00:00:00Z",
    updated_at: "2024-10-12T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-005",
    agent_id: "agent-001",
    title: "Sea-view Studio at PIK Avenue",
    description:
      "Modern studio steps from PIK Avenue mall and the marina. Stunning sea views from upper floors. Perfect for young professionals.",
    price_monthly: 7500000,
    area: "PIK",
    address: "Pantai Indah Kapuk, Jakarta Utara",
    lat: -6.1036,
    lng: 106.7326,
    bedrooms: 0,
    bathrooms: 1,
    size_sqm: 24,
    furnished: "fully-furnished",
    is_pet_friendly: false,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "WiFi", "Pool", "Gym", "Security 24/7", "Elevator"],
    created_at: "2024-10-08T00:00:00Z",
    updated_at: "2024-10-14T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-006",
    agent_id: "agent-001",
    title: "Heritage Villa Pondok Indah",
    description:
      "Grand villa in Jakarta's most prestigious residential address. Mature trees, private pool, five-car garage. Rarely available.",
    price_monthly: 55000000,
    area: "Pondok Indah",
    address: "Jl. Pondok Indah Raya No. 88, Jakarta Selatan",
    lat: -6.265,
    lng: 106.784,
    bedrooms: 4,
    bathrooms: 4,
    size_sqm: 450,
    furnished: "unfurnished",
    is_pet_friendly: true,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "Pool", "Gym", "Garden", "Parking", "Security 24/7", "CCTV", "Intercom"],
    created_at: "2024-08-01T00:00:00Z",
    updated_at: "2024-10-01T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-007",
    agent_id: "agent-001",
    title: "Modern 2BR Kelapa Gading Square",
    description:
      "Move-in ready apartment above La Piazza Kelapa Gading. Vibrant F&B scene, good transport links, family-friendly.",
    price_monthly: 14000000,
    area: "Kelapa Gading",
    address: "Kelapa Gading Square, Jakarta Utara",
    lat: -6.1618,
    lng: 106.9067,
    bedrooms: 2,
    bathrooms: 1,
    size_sqm: 62,
    furnished: "fully-furnished",
    is_pet_friendly: false,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "WiFi", "Pool", "Security 24/7", "Elevator", "Balcony"],
    created_at: "2024-09-28T00:00:00Z",
    updated_at: "2024-10-11T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
  {
    id: "listing-008",
    agent_id: "agent-001",
    title: "Penthouse 3BR Senayan City Tower",
    description:
      "Ultra-premium penthouse above Senayan City mall. Private lift lobby, wrap-around terrace, bespoke Italian kitchen.",
    price_monthly: 42000000,
    area: "Senayan",
    address: "Senayan City Tower Residence, Jakarta Pusat",
    lat: -6.2262,
    lng: 106.7981,
    bedrooms: 3,
    bathrooms: 3,
    size_sqm: 280,
    furnished: "fully-furnished",
    is_pet_friendly: false,
    is_verified: true,
    status: "active",
    photos: [],
    amenities: ["AC", "WiFi", "Pool", "Gym", "Security 24/7", "Elevator", "Balcony", "CCTV"],
    created_at: "2024-07-15T00:00:00Z",
    updated_at: "2024-10-09T00:00:00Z",
    agent: SAMPLE_AGENT,
  },
];
